# Site settings
title: Tim Martin
email: tim@timmart.in
description: > # this means to ignore newlines until "baseurl:"
  I write code and talk about tech here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timmart.in" # the base hostname & protocol for your site
twitter_username: tmmrtn
github_username:  t-mart
disqus_shortname:  timmartin

exclude: [venv, Gemfile, Gemfile.lock, Gruntfile.js, package.json, README, requirements.txt, vendor]

markdown: kramdown

permalink: /:title.html

highlighter: pygments

assets:
  sources:
    - _assets

